spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&characterEncoding=UTF-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp


file:
  upload:
    path: /Users/leekyunghee/works/springboot-mvc-jsp/src/main/webapp/WEB-INF/uploadFiles/

logging:
        level:
              com.example.demo.board: debug